/* 
    Copyright (c) 2012 Microsoft Corporation.  All rights reserved.
    Use of this sample source code is subject to the terms of the Microsoft license 
    agreement under which you licensed this sample source code and is provided AS-IS.
    If you did not accept the terms of the license agreement, you are not authorized 
    to use this sample source code.  For the terms of the license, please see the 
    license agreement between you and Microsoft.
  
    To see all Code Samples for Windows Phone, visit http://go.microsoft.com/fwlink/?LinkID=219604 
  
*/
namespace sdkWalletMembershipDealsWP8CS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdkWalletMembershipDealsWP8CS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVENTUREWORKS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons.
        /// </summary>
        public static string CouponsListItem {
            get {
                return ResourceManager.GetString("CouponsListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string CouponsTitle {
            get {
                return ResourceManager.GetString("CouponsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete membership.
        /// </summary>
        public static string DeleteMembershipButtonText {
            get {
                return ResourceManager.GetString("DeleteMembershipButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap coupons to see Adventure Works&apos; current promotions..
        /// </summary>
        public static string MainViewCouponInstructions {
            get {
                return ResourceManager.GetString("MainViewCouponInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap membership to manage your Adventure Works membership..
        /// </summary>
        public static string MainViewMembershipInstructions {
            get {
                return ResourceManager.GetString("MainViewMembershipInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Adventure Works Wallet Application..
        /// </summary>
        public static string MainViewWelcome {
            get {
                return ResourceManager.GetString("MainViewWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to membership.
        /// </summary>
        public static string MembershipListItem {
            get {
                return ResourceManager.GetString("MembershipListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Number.
        /// </summary>
        public static string MembershipNumberLabel {
            get {
                return ResourceManager.GetString("MembershipNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string MembershipTitle {
            get {
                return ResourceManager.GetString("MembershipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure Works.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from wallet.
        /// </summary>
        public static string RemoveFromWalletButtonText {
            get {
                return ResourceManager.GetString("RemoveFromWalletButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save to wallet.
        /// </summary>
        public static string SaveToWalletButtonText {
            get {
                return ResourceManager.GetString("SaveToWalletButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        public static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get an Adventure Works membership, enter your information and tap join below..
        /// </summary>
        public static string SignUpInstructions {
            get {
                return ResourceManager.GetString("SignUpInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
    }
}
