
   
 
 
 
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataWinPhoneQuickstart.DataServiceContext.Netflix	
{
	public partial class NetflixCatalog: global::System.Data.Services.Client.DataServiceContext
	{
	public NetflixCatalog(global::System.Uri serviceRoot) : 
                base(serviceRoot)
    	{
        	this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
        	this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
        	this.OnContextCreated();
    	}
		
		protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Netflix.Catalog.v2", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ODataWinPhoneQuickstart.DataServiceContext.Netflix", typeName.Substring(18)), false);
            }
            return null;
        }

        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ODataWinPhoneQuickstart.DataServiceContext.Netflix", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Netflix.Catalog.v2.", clientType.Name);
            }
            return null;
        }
		
	    partial void OnContextCreated();
		
		public global::System.Data.Services.Client.DataServiceQuery< Genre> Genres
        {
            get
            {
                if ((this._Genres == null))
                {
                    this._Genres = base.CreateQuery< Genre >("Genres");
                }
                return this._Genres;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< Genre > _Genres;		
		public void AddToGenres(Genre genre)
        {
            base.AddObject("Genres", genre);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< Title> Titles
        {
            get
            {
                if ((this._Titles == null))
                {
                    this._Titles = base.CreateQuery< Title >("Titles");
                }
                return this._Titles;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< Title > _Titles;		
		public void AddToTitles(Title title)
        {
            base.AddObject("Titles", title);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< TitleAudioFormat> TitleAudioFormats
        {
            get
            {
                if ((this._TitleAudioFormats == null))
                {
                    this._TitleAudioFormats = base.CreateQuery< TitleAudioFormat >("TitleAudioFormats");
                }
                return this._TitleAudioFormats;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< TitleAudioFormat > _TitleAudioFormats;		
		public void AddToTitleAudioFormats(TitleAudioFormat titleAudioFormat)
        {
            base.AddObject("TitleAudioFormats", titleAudioFormat);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< TitleAward> TitleAwards
        {
            get
            {
                if ((this._TitleAwards == null))
                {
                    this._TitleAwards = base.CreateQuery< TitleAward >("TitleAwards");
                }
                return this._TitleAwards;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< TitleAward > _TitleAwards;		
		public void AddToTitleAwards(TitleAward titleAward)
        {
            base.AddObject("TitleAwards", titleAward);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery< Person >("People");
                }
                return this._People;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< Person > _People;		
		public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< TitleScreenFormat> TitleScreenFormats
        {
            get
            {
                if ((this._TitleScreenFormats == null))
                {
                    this._TitleScreenFormats = base.CreateQuery< TitleScreenFormat >("TitleScreenFormats");
                }
                return this._TitleScreenFormats;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< TitleScreenFormat > _TitleScreenFormats;		
		public void AddToTitleScreenFormats(TitleScreenFormat titleScreenFormat)
        {
            base.AddObject("TitleScreenFormats", titleScreenFormat);
        }
		
		public global::System.Data.Services.Client.DataServiceQuery< Language> Languages
        {
            get
            {
                if ((this._Languages == null))
                {
                    this._Languages = base.CreateQuery< Language >("Languages");
                }
                return this._Languages;
            }
        }
		private global::System.Data.Services.Client.DataServiceQuery< Language > _Languages;		
		public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
		
	}
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="NetflixCatalog")]
	public partial class NetflixCatalogLocalDB  : global::System.Data.Linq.DataContext
	{
		// Define a default connection string, in case one isn't supplied.
		public static string defaultDbString = "Data Source=isostore:/NetflixCatalog.sdf";

		// Pass a user-supplied connection string to the base class.
		public NetflixCatalogLocalDB(string connectionString)
			: base(connectionString)
		{ }

		// Pass the default connection string to the base class.
		public NetflixCatalogLocalDB()
			: base(defaultDbString)
		{ }
		public global::System.Data.Linq.Table<Genre> Genres;		
		public global::System.Data.Linq.Table<Title> Titles;		
		public global::System.Data.Linq.Table<TitleAudioFormat> TitleAudioFormats;		
		public global::System.Data.Linq.Table<TitleAward> TitleAwards;		
		public global::System.Data.Linq.Table<Person> People;		
		public global::System.Data.Linq.Table<TitleScreenFormat> TitleScreenFormats;		
		public global::System.Data.Linq.Table<Language> Languages;		
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("Genres")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("Name", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]		
	[global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
	public partial class Genre: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  Genre CreateGenre(string name)
		{
			Genre genre = new Genre();
			genre.Name = name;
			return genre;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
				this.OnNameChanging(value);
				this._Name = value;
				this.OnNameChanged();
				this.OnPropertyChanged("Name");
            }
        }		 	
		private  string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

	    public global::System.Data.Services.Client.DataServiceCollection<Title> Titles
        {
            get
            {
                return this._Titles;
            }
            set
            {
				this._Titles = value;
				this.OnPropertyChanged("Titles");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _Titles = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("Titles")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("Name", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]		
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("Synopsis", global::System.Data.Services.Common.SyndicationItemProperty.Summary, global::System.Data.Services.Common.SyndicationTextContentKind.Html, true)]		
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("DateModified", global::System.Data.Services.Common.SyndicationItemProperty.Updated, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]		
	[global::System.Data.Services.Common.HasStreamAttribute()]	
	[global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
	public partial class Title: global::System.ComponentModel.INotifyPropertyChanged
	{

			public Title()
			{
			    // We need to explicitly instantiate complex properties or L2S fails.
			    this.BluRay = new DeliveryFormatAvailability();
			    this.BoxArt = new BoxArt();
			    this.Dvd = new DeliveryFormatAvailability();
			    this.Instant = new InstantAvailability();
			}

			public  static  Title CreateTitle(string id , global::System.DateTime dateModified , DeliveryFormatAvailability bluRay , BoxArt boxArt , DeliveryFormatAvailability dvd , InstantAvailability instant)
		{
			Title title = new Title();
			title.Id = id;
			title.DateModified = dateModified;
			title.BluRay = bluRay;
			title.BoxArt = boxArt;
			title.Dvd = dvd;
			title.Instant = instant;
			return title;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
				this.OnIdChanging(value);
				this._Id = value;
				this.OnIdChanged();
				this.OnPropertyChanged("Id");
            }
        }		 	
		private  string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
				this.OnNameChanging(value);
				this._Name = value;
				this.OnNameChanged();
				this.OnPropertyChanged("Name");
            }
        }		 	
		private  string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
				this.OnShortNameChanging(value);
				this._ShortName = value;
				this.OnShortNameChanged();
				this.OnPropertyChanged("ShortName");
            }
        }		 	
		private  string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Synopsis
        {
            get
            {
                return this._Synopsis;
            }
            set
            {
				this.OnSynopsisChanging(value);
				this._Synopsis = value;
				this.OnSynopsisChanged();
				this.OnPropertyChanged("Synopsis");
            }
        }		 	
		private  string _Synopsis;
        partial void OnSynopsisChanging(string value);
        partial void OnSynopsisChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string ShortSynopsis
        {
            get
            {
                return this._ShortSynopsis;
            }
            set
            {
				this.OnShortSynopsisChanging(value);
				this._ShortSynopsis = value;
				this.OnShortSynopsisChanged();
				this.OnPropertyChanged("ShortSynopsis");
            }
        }		 	
		private  string _ShortSynopsis;
        partial void OnShortSynopsisChanging(string value);
        partial void OnShortSynopsisChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<double> AverageRating
        {
            get
            {
                return this._AverageRating;
            }
            set
            {
				this.OnAverageRatingChanging(value);
				this._AverageRating = value;
				this.OnAverageRatingChanged();
				this.OnPropertyChanged("AverageRating");
            }
        }		 	
		private  global::System.Nullable<double> _AverageRating;
        partial void OnAverageRatingChanging(global::System.Nullable<double> value);
        partial void OnAverageRatingChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<int> ReleaseYear
        {
            get
            {
                return this._ReleaseYear;
            }
            set
            {
				this.OnReleaseYearChanging(value);
				this._ReleaseYear = value;
				this.OnReleaseYearChanged();
				this.OnPropertyChanged("ReleaseYear");
            }
        }		 	
		private  global::System.Nullable<int> _ReleaseYear;
        partial void OnReleaseYearChanging(global::System.Nullable<int> value);
        partial void OnReleaseYearChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
				this.OnUrlChanging(value);
				this._Url = value;
				this.OnUrlChanged();
				this.OnPropertyChanged("Url");
            }
        }		 	
		private  string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<int> Runtime
        {
            get
            {
                return this._Runtime;
            }
            set
            {
				this.OnRuntimeChanging(value);
				this._Runtime = value;
				this.OnRuntimeChanged();
				this.OnPropertyChanged("Runtime");
            }
        }		 	
		private  global::System.Nullable<int> _Runtime;
        partial void OnRuntimeChanging(global::System.Nullable<int> value);
        partial void OnRuntimeChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
				this.OnRatingChanging(value);
				this._Rating = value;
				this.OnRatingChanged();
				this.OnPropertyChanged("Rating");
            }
        }		 	
		private  string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
	    public global::System.DateTime DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
				this.OnDateModifiedChanging(value);
				this._DateModified = value;
				this.OnDateModifiedChanged();
				this.OnPropertyChanged("DateModified");
            }
        }		 	
		private  global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
				this.OnTypeChanging(value);
				this._Type = value;
				this.OnTypeChanged();
				this.OnPropertyChanged("Type");
            }
        }		 	
		private  string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string WebsiteUrl
        {
            get
            {
                return this._WebsiteUrl;
            }
            set
            {
				this.OnWebsiteUrlChanging(value);
				this._WebsiteUrl = value;
				this.OnWebsiteUrlChanged();
				this.OnPropertyChanged("WebsiteUrl");
            }
        }		 	
		private  string _WebsiteUrl;
        partial void OnWebsiteUrlChanging(string value);
        partial void OnWebsiteUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string NetflixApiId
        {
            get
            {
                return this._NetflixApiId;
            }
            set
            {
				this.OnNetflixApiIdChanging(value);
				this._NetflixApiId = value;
				this.OnNetflixApiIdChanged();
				this.OnPropertyChanged("NetflixApiId");
            }
        }		 	
		private  string _NetflixApiId;
        partial void OnNetflixApiIdChanging(string value);
        partial void OnNetflixApiIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string TinyUrl
        {
            get
            {
                return this._TinyUrl;
            }
            set
            {
				this.OnTinyUrlChanging(value);
				this._TinyUrl = value;
				this.OnTinyUrlChanged();
				this.OnPropertyChanged("TinyUrl");
            }
        }		 	
		private  string _TinyUrl;
        partial void OnTinyUrlChanging(string value);
        partial void OnTinyUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
	    public DeliveryFormatAvailability BluRay
        {
            get
            {
                if (((this._BluRay == null) 
                            && (this._BluRayInitialized != true)))
                {
                    this._BluRay = new DeliveryFormatAvailability();
                    this._BluRayInitialized = true;
                }
                return this._BluRay;
            }
            set
            {
				this.OnBluRayChanging(value);
				this._BluRay = value;
				this._BluRayInitialized = true;
				this.OnBluRayChanged();
				this.OnPropertyChanged("BluRay");
            }
        }		 	
		private  DeliveryFormatAvailability _BluRay;
		private bool _BluRayInitialized;
        partial void OnBluRayChanging(DeliveryFormatAvailability value);
        partial void OnBluRayChanged();

		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
		private global::System.Boolean BluRay_Available
		{
			get { return this.BluRay.Available; }
			set { this.BluRay.Available = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? BluRay_AvailableFrom
		{
			get { return this.BluRay.AvailableFrom; }
			set { this.BluRay.AvailableFrom = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? BluRay_AvailableTo
		{
			get { return this.BluRay.AvailableTo; }
			set { this.BluRay.AvailableTo = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String BluRay_Rating
		{
			get { return this.BluRay.Rating; }
			set { this.BluRay.Rating = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.Int32? BluRay_Runtime
		{
			get { return this.BluRay.Runtime; }
			set { this.BluRay.Runtime = value; }			
		}
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
	    public BoxArt BoxArt
        {
            get
            {
                if (((this._BoxArt == null) 
                            && (this._BoxArtInitialized != true)))
                {
                    this._BoxArt = new BoxArt();
                    this._BoxArtInitialized = true;
                }
                return this._BoxArt;
            }
            set
            {
				this.OnBoxArtChanging(value);
				this._BoxArt = value;
				this._BoxArtInitialized = true;
				this.OnBoxArtChanged();
				this.OnPropertyChanged("BoxArt");
            }
        }		 	
		private  BoxArt _BoxArt;
		private bool _BoxArtInitialized;
        partial void OnBoxArtChanging(BoxArt value);
        partial void OnBoxArtChanged();

		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String BoxArt_SmallUrl
		{
			get { return this.BoxArt.SmallUrl; }
			set { this.BoxArt.SmallUrl = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String BoxArt_MediumUrl
		{
			get { return this.BoxArt.MediumUrl; }
			set { this.BoxArt.MediumUrl = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String BoxArt_LargeUrl
		{
			get { return this.BoxArt.LargeUrl; }
			set { this.BoxArt.LargeUrl = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String BoxArt_HighDefinitionUrl
		{
			get { return this.BoxArt.HighDefinitionUrl; }
			set { this.BoxArt.HighDefinitionUrl = value; }			
		}
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
	    public DeliveryFormatAvailability Dvd
        {
            get
            {
                if (((this._Dvd == null) 
                            && (this._DvdInitialized != true)))
                {
                    this._Dvd = new DeliveryFormatAvailability();
                    this._DvdInitialized = true;
                }
                return this._Dvd;
            }
            set
            {
				this.OnDvdChanging(value);
				this._Dvd = value;
				this._DvdInitialized = true;
				this.OnDvdChanged();
				this.OnPropertyChanged("Dvd");
            }
        }		 	
		private  DeliveryFormatAvailability _Dvd;
		private bool _DvdInitialized;
        partial void OnDvdChanging(DeliveryFormatAvailability value);
        partial void OnDvdChanged();

		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
		private global::System.Boolean Dvd_Available
		{
			get { return this.Dvd.Available; }
			set { this.Dvd.Available = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? Dvd_AvailableFrom
		{
			get { return this.Dvd.AvailableFrom; }
			set { this.Dvd.AvailableFrom = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? Dvd_AvailableTo
		{
			get { return this.Dvd.AvailableTo; }
			set { this.Dvd.AvailableTo = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String Dvd_Rating
		{
			get { return this.Dvd.Rating; }
			set { this.Dvd.Rating = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.Int32? Dvd_Runtime
		{
			get { return this.Dvd.Runtime; }
			set { this.Dvd.Runtime = value; }			
		}
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
	    public InstantAvailability Instant
        {
            get
            {
                if (((this._Instant == null) 
                            && (this._InstantInitialized != true)))
                {
                    this._Instant = new InstantAvailability();
                    this._InstantInitialized = true;
                }
                return this._Instant;
            }
            set
            {
				this.OnInstantChanging(value);
				this._Instant = value;
				this._InstantInitialized = true;
				this.OnInstantChanged();
				this.OnPropertyChanged("Instant");
            }
        }		 	
		private  InstantAvailability _Instant;
		private bool _InstantInitialized;
        partial void OnInstantChanging(InstantAvailability value);
        partial void OnInstantChanged();

		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
		private global::System.Boolean Instant_Available
		{
			get { return this.Instant.Available; }
			set { this.Instant.Available = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? Instant_AvailableFrom
		{
			get { return this.Instant.AvailableFrom; }
			set { this.Instant.AvailableFrom = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.DateTime? Instant_AvailableTo
		{
			get { return this.Instant.AvailableTo; }
			set { this.Instant.AvailableTo = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
		private global::System.Boolean Instant_HighDefinitionAvailable
		{
			get { return this.Instant.HighDefinitionAvailable; }
			set { this.Instant.HighDefinitionAvailable = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.String Instant_Rating
		{
			get { return this.Instant.Rating; }
			set { this.Instant.Rating = value; }			
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute]
		private global::System.Int32? Instant_Runtime
		{
			get { return this.Instant.Runtime; }
			set { this.Instant.Runtime = value; }			
		}
	    public Title Disc
        {
            get
            {
                return this._Disc;
            }
            set
            {
				this._Disc = value;
				this.OnPropertyChanged("Disc");
            }
        }		 	
		private  Title _Disc;

	    public Title Season
        {
            get
            {
                return this._Season;
            }
            set
            {
				this._Season = value;
				this.OnPropertyChanged("Season");
            }
        }		 	
		private  Title _Season;

	    public Title Series
        {
            get
            {
                return this._Series;
            }
            set
            {
				this._Series = value;
				this.OnPropertyChanged("Series");
            }
        }		 	
		private  Title _Series;

	    public Title Movie
        {
            get
            {
                return this._Movie;
            }
            set
            {
				this._Movie = value;
				this.OnPropertyChanged("Movie");
            }
        }		 	
		private  Title _Movie;

	    public global::System.Data.Services.Client.DataServiceCollection<TitleAudioFormat> AudioFormats
        {
            get
            {
                return this._AudioFormats;
            }
            set
            {
				this._AudioFormats = value;
				this.OnPropertyChanged("AudioFormats");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<TitleAudioFormat> _AudioFormats = new global::System.Data.Services.Client.DataServiceCollection<TitleAudioFormat>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<TitleAward> Awards
        {
            get
            {
                return this._Awards;
            }
            set
            {
				this._Awards = value;
				this.OnPropertyChanged("Awards");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<TitleAward> _Awards = new global::System.Data.Services.Client.DataServiceCollection<TitleAward>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<TitleScreenFormat> ScreenFormats
        {
            get
            {
                return this._ScreenFormats;
            }
            set
            {
				this._ScreenFormats = value;
				this.OnPropertyChanged("ScreenFormats");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<TitleScreenFormat> _ScreenFormats = new global::System.Data.Services.Client.DataServiceCollection<TitleScreenFormat>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Language> Languages
        {
            get
            {
                return this._Languages;
            }
            set
            {
				this._Languages = value;
				this.OnPropertyChanged("Languages");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Language> _Languages = new global::System.Data.Services.Client.DataServiceCollection<Language>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Person> Cast
        {
            get
            {
                return this._Cast;
            }
            set
            {
				this._Cast = value;
				this.OnPropertyChanged("Cast");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Person> _Cast = new global::System.Data.Services.Client.DataServiceCollection<Person>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Person> Directors
        {
            get
            {
                return this._Directors;
            }
            set
            {
				this._Directors = value;
				this.OnPropertyChanged("Directors");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Person> _Directors = new global::System.Data.Services.Client.DataServiceCollection<Person>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Title> Discs
        {
            get
            {
                return this._Discs;
            }
            set
            {
				this._Discs = value;
				this.OnPropertyChanged("Discs");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _Discs = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Title> Episodes
        {
            get
            {
                return this._Episodes;
            }
            set
            {
				this._Episodes = value;
				this.OnPropertyChanged("Episodes");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _Episodes = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Genre> Genres
        {
            get
            {
                return this._Genres;
            }
            set
            {
				this._Genres = value;
				this.OnPropertyChanged("Genres");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Genre> _Genres = new global::System.Data.Services.Client.DataServiceCollection<Genre>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Title> Seasons
        {
            get
            {
                return this._Seasons;
            }
            set
            {
				this._Seasons = value;
				this.OnPropertyChanged("Seasons");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _Seasons = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("TitleAudioFormats")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.DataServiceKeyAttribute("TitleId", "DeliveryFormat", "Language", "Format")]
	public partial class TitleAudioFormat: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  TitleAudioFormat CreateTitleAudioFormat(string titleId , string deliveryFormat , string language , string format)
		{
			TitleAudioFormat titleaudioformat = new TitleAudioFormat();
			titleaudioformat.TitleId = titleId;
			titleaudioformat.DeliveryFormat = deliveryFormat;
			titleaudioformat.Language = language;
			titleaudioformat.Format = format;
			return titleaudioformat;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string TitleId
        {
            get
            {
                return this._TitleId;
            }
            set
            {
				this.OnTitleIdChanging(value);
				this._TitleId = value;
				this.OnTitleIdChanged();
				this.OnPropertyChanged("TitleId");
            }
        }		 	
		private  string _TitleId;
        partial void OnTitleIdChanging(string value);
        partial void OnTitleIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string DeliveryFormat
        {
            get
            {
                return this._DeliveryFormat;
            }
            set
            {
				this.OnDeliveryFormatChanging(value);
				this._DeliveryFormat = value;
				this.OnDeliveryFormatChanged();
				this.OnPropertyChanged("DeliveryFormat");
            }
        }		 	
		private  string _DeliveryFormat;
        partial void OnDeliveryFormatChanging(string value);
        partial void OnDeliveryFormatChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
				this.OnLanguageChanging(value);
				this._Language = value;
				this.OnLanguageChanged();
				this.OnPropertyChanged("Language");
            }
        }		 	
		private  string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Format
        {
            get
            {
                return this._Format;
            }
            set
            {
				this.OnFormatChanging(value);
				this._Format = value;
				this.OnFormatChanged();
				this.OnPropertyChanged("Format");
            }
        }		 	
		private  string _Format;
        partial void OnFormatChanging(string value);
        partial void OnFormatChanged();

	    public Title Title
        {
            get
            {
                return this._Title;
            }
            set
            {
				this._Title = value;
				this.OnPropertyChanged("Title");
            }
        }		 	
		private  Title _Title;

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("TitleAwards")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
	public partial class TitleAward: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  TitleAward CreateTitleAward(global::System.Guid id , bool won)
		{
			TitleAward titleaward = new TitleAward();
			titleaward.Id = id;
			titleaward.Won = won;
			return titleaward;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
				this.OnIdChanging(value);
				this._Id = value;
				this.OnIdChanged();
				this.OnPropertyChanged("Id");
            }
        }		 	
		private  global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
				this.OnTypeChanging(value);
				this._Type = value;
				this.OnTypeChanged();
				this.OnPropertyChanged("Type");
            }
        }		 	
		private  string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
				this.OnCategoryChanging(value);
				this._Category = value;
				this.OnCategoryChanged();
				this.OnPropertyChanged("Category");
            }
        }		 	
		private  string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<int> Year
        {
            get
            {
                return this._Year;
            }
            set
            {
				this.OnYearChanging(value);
				this._Year = value;
				this.OnYearChanged();
				this.OnPropertyChanged("Year");
            }
        }		 	
		private  global::System.Nullable<int> _Year;
        partial void OnYearChanging(global::System.Nullable<int> value);
        partial void OnYearChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
	    public bool Won
        {
            get
            {
                return this._Won;
            }
            set
            {
				this.OnWonChanging(value);
				this._Won = value;
				this.OnWonChanged();
				this.OnPropertyChanged("Won");
            }
        }		 	
		private  bool _Won;
        partial void OnWonChanging(bool value);
        partial void OnWonChanged();

	    public Person Person
        {
            get
            {
                return this._Person;
            }
            set
            {
				this._Person = value;
				this.OnPropertyChanged("Person");
            }
        }		 	
		private  Person _Person;

	    public Title Title
        {
            get
            {
                return this._Title;
            }
            set
            {
				this._Title = value;
				this.OnPropertyChanged("Title");
            }
        }		 	
		private  Title _Title;

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("People")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("Name", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]		
	[global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
	public partial class Person: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  Person CreatePerson(int id)
		{
			Person person = new Person();
			person.Id = id;
			return person;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
				this.OnIdChanging(value);
				this._Id = value;
				this.OnIdChanged();
				this.OnPropertyChanged("Id");
            }
        }		 	
		private  int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
				this.OnNameChanging(value);
				this._Name = value;
				this.OnNameChanged();
				this.OnPropertyChanged("Name");
            }
        }		 	
		private  string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

	    public global::System.Data.Services.Client.DataServiceCollection<TitleAward> Awards
        {
            get
            {
                return this._Awards;
            }
            set
            {
				this._Awards = value;
				this.OnPropertyChanged("Awards");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<TitleAward> _Awards = new global::System.Data.Services.Client.DataServiceCollection<TitleAward>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Title> TitlesActedIn
        {
            get
            {
                return this._TitlesActedIn;
            }
            set
            {
				this._TitlesActedIn = value;
				this.OnPropertyChanged("TitlesActedIn");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _TitlesActedIn = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

	    public global::System.Data.Services.Client.DataServiceCollection<Title> TitlesDirected
        {
            get
            {
                return this._TitlesDirected;
            }
            set
            {
				this._TitlesDirected = value;
				this.OnPropertyChanged("TitlesDirected");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _TitlesDirected = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("TitleScreenFormats")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.DataServiceKeyAttribute("TitleId", "DeliveryFormat", "Format")]
	public partial class TitleScreenFormat: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  TitleScreenFormat CreateTitleScreenFormat(string titleId , string deliveryFormat , string format)
		{
			TitleScreenFormat titlescreenformat = new TitleScreenFormat();
			titlescreenformat.TitleId = titleId;
			titlescreenformat.DeliveryFormat = deliveryFormat;
			titlescreenformat.Format = format;
			return titlescreenformat;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string TitleId
        {
            get
            {
                return this._TitleId;
            }
            set
            {
				this.OnTitleIdChanging(value);
				this._TitleId = value;
				this.OnTitleIdChanged();
				this.OnPropertyChanged("TitleId");
            }
        }		 	
		private  string _TitleId;
        partial void OnTitleIdChanging(string value);
        partial void OnTitleIdChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string DeliveryFormat
        {
            get
            {
                return this._DeliveryFormat;
            }
            set
            {
				this.OnDeliveryFormatChanging(value);
				this._DeliveryFormat = value;
				this.OnDeliveryFormatChanged();
				this.OnPropertyChanged("DeliveryFormat");
            }
        }		 	
		private  string _DeliveryFormat;
        partial void OnDeliveryFormatChanging(string value);
        partial void OnDeliveryFormatChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Format
        {
            get
            {
                return this._Format;
            }
            set
            {
				this.OnFormatChanging(value);
				this._Format = value;
				this.OnFormatChanged();
				this.OnPropertyChanged("Format");
            }
        }		 	
		private  string _Format;
        partial void OnFormatChanging(string value);
        partial void OnFormatChanged();

	    public Title Title
        {
            get
            {
                return this._Title;
            }
            set
            {
				this._Title = value;
				this.OnPropertyChanged("Title");
            }
        }		 	
		private  Title _Title;

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	[global::System.Data.Services.Common.EntitySetAttribute("Languages")]	
	[global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]	
	[global::System.Data.Linq.Mapping.TableAttribute]
	[global::System.Data.Services.Common.EntityPropertyMappingAttribute("Name", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]		
	[global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
	public partial class Language: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  Language CreateLanguage(string name)
		{
			Language language = new Language();
			language.Name = name;
			return language;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false, IsPrimaryKey=true)]
	    public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
				this.OnNameChanging(value);
				this._Name = value;
				this.OnNameChanged();
				this.OnPropertyChanged("Name");
            }
        }		 	
		private  string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

	    public global::System.Data.Services.Client.DataServiceCollection<Title> Titles
        {
            get
            {
                return this._Titles;
            }
            set
            {
				this._Titles = value;
				this.OnPropertyChanged("Titles");
            }
        }		 	
		private  global::System.Data.Services.Client.DataServiceCollection<Title> _Titles = new global::System.Data.Services.Client.DataServiceCollection<Title>(null, global::System.Data.Services.Client.TrackingMode.None);

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	public partial class DeliveryFormatAvailability: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  DeliveryFormatAvailability CreateDeliveryFormatAvailability(bool available)
		{
			DeliveryFormatAvailability deliveryformatavailability = new DeliveryFormatAvailability();
			deliveryformatavailability.Available = available;
			return deliveryformatavailability;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
	    public bool Available
        {
            get
            {
                return this._Available;
            }
            set
            {
				this.OnAvailableChanging(value);
				this._Available = value;
				this.OnAvailableChanged();
				this.OnPropertyChanged("Available");
            }
        }		 	
		private  bool _Available;
        partial void OnAvailableChanging(bool value);
        partial void OnAvailableChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<global::System.DateTime> AvailableFrom
        {
            get
            {
                return this._AvailableFrom;
            }
            set
            {
				this.OnAvailableFromChanging(value);
				this._AvailableFrom = value;
				this.OnAvailableFromChanged();
				this.OnPropertyChanged("AvailableFrom");
            }
        }		 	
		private  global::System.Nullable<global::System.DateTime> _AvailableFrom;
        partial void OnAvailableFromChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAvailableFromChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<global::System.DateTime> AvailableTo
        {
            get
            {
                return this._AvailableTo;
            }
            set
            {
				this.OnAvailableToChanging(value);
				this._AvailableTo = value;
				this.OnAvailableToChanged();
				this.OnPropertyChanged("AvailableTo");
            }
        }		 	
		private  global::System.Nullable<global::System.DateTime> _AvailableTo;
        partial void OnAvailableToChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAvailableToChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
				this.OnRatingChanging(value);
				this._Rating = value;
				this.OnRatingChanged();
				this.OnPropertyChanged("Rating");
            }
        }		 	
		private  string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<int> Runtime
        {
            get
            {
                return this._Runtime;
            }
            set
            {
				this.OnRuntimeChanging(value);
				this._Runtime = value;
				this.OnRuntimeChanged();
				this.OnPropertyChanged("Runtime");
            }
        }		 	
		private  global::System.Nullable<int> _Runtime;
        partial void OnRuntimeChanging(global::System.Nullable<int> value);
        partial void OnRuntimeChanged();

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	public partial class BoxArt: global::System.ComponentModel.INotifyPropertyChanged
	{
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string SmallUrl
        {
            get
            {
                return this._SmallUrl;
            }
            set
            {
				this.OnSmallUrlChanging(value);
				this._SmallUrl = value;
				this.OnSmallUrlChanged();
				this.OnPropertyChanged("SmallUrl");
            }
        }		 	
		private  string _SmallUrl;
        partial void OnSmallUrlChanging(string value);
        partial void OnSmallUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string MediumUrl
        {
            get
            {
                return this._MediumUrl;
            }
            set
            {
				this.OnMediumUrlChanging(value);
				this._MediumUrl = value;
				this.OnMediumUrlChanged();
				this.OnPropertyChanged("MediumUrl");
            }
        }		 	
		private  string _MediumUrl;
        partial void OnMediumUrlChanging(string value);
        partial void OnMediumUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string LargeUrl
        {
            get
            {
                return this._LargeUrl;
            }
            set
            {
				this.OnLargeUrlChanging(value);
				this._LargeUrl = value;
				this.OnLargeUrlChanged();
				this.OnPropertyChanged("LargeUrl");
            }
        }		 	
		private  string _LargeUrl;
        partial void OnLargeUrlChanging(string value);
        partial void OnLargeUrlChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string HighDefinitionUrl
        {
            get
            {
                return this._HighDefinitionUrl;
            }
            set
            {
				this.OnHighDefinitionUrlChanging(value);
				this._HighDefinitionUrl = value;
				this.OnHighDefinitionUrlChanged();
				this.OnPropertyChanged("HighDefinitionUrl");
            }
        }		 	
		private  string _HighDefinitionUrl;
        partial void OnHighDefinitionUrlChanging(string value);
        partial void OnHighDefinitionUrlChanged();

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
	public partial class InstantAvailability: global::System.ComponentModel.INotifyPropertyChanged
	{
		public  static  InstantAvailability CreateInstantAvailability(bool available , bool highDefinitionAvailable)
		{
			InstantAvailability instantavailability = new InstantAvailability();
			instantavailability.Available = available;
			instantavailability.HighDefinitionAvailable = highDefinitionAvailable;
			return instantavailability;
		}
		
	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
	    public bool Available
        {
            get
            {
                return this._Available;
            }
            set
            {
				this.OnAvailableChanging(value);
				this._Available = value;
				this.OnAvailableChanged();
				this.OnPropertyChanged("Available");
            }
        }		 	
		private  bool _Available;
        partial void OnAvailableChanging(bool value);
        partial void OnAvailableChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<global::System.DateTime> AvailableFrom
        {
            get
            {
                return this._AvailableFrom;
            }
            set
            {
				this.OnAvailableFromChanging(value);
				this._AvailableFrom = value;
				this.OnAvailableFromChanged();
				this.OnPropertyChanged("AvailableFrom");
            }
        }		 	
		private  global::System.Nullable<global::System.DateTime> _AvailableFrom;
        partial void OnAvailableFromChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAvailableFromChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<global::System.DateTime> AvailableTo
        {
            get
            {
                return this._AvailableTo;
            }
            set
            {
				this.OnAvailableToChanging(value);
				this._AvailableTo = value;
				this.OnAvailableToChanged();
				this.OnPropertyChanged("AvailableTo");
            }
        }		 	
		private  global::System.Nullable<global::System.DateTime> _AvailableTo;
        partial void OnAvailableToChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAvailableToChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=false)]
	    public bool HighDefinitionAvailable
        {
            get
            {
                return this._HighDefinitionAvailable;
            }
            set
            {
				this.OnHighDefinitionAvailableChanging(value);
				this._HighDefinitionAvailable = value;
				this.OnHighDefinitionAvailableChanged();
				this.OnPropertyChanged("HighDefinitionAvailable");
            }
        }		 	
		private  bool _HighDefinitionAvailable;
        partial void OnHighDefinitionAvailableChanging(bool value);
        partial void OnHighDefinitionAvailableChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
				this.OnRatingChanging(value);
				this._Rating = value;
				this.OnRatingChanged();
				this.OnPropertyChanged("Rating");
            }
        }		 	
		private  string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();

	    [global::System.Runtime.Serialization.DataMemberAttribute()]
		[global::System.Data.Linq.Mapping.ColumnAttribute(CanBeNull=true)]
	    public global::System.Nullable<int> Runtime
        {
            get
            {
                return this._Runtime;
            }
            set
            {
				this.OnRuntimeChanging(value);
				this._Runtime = value;
				this.OnRuntimeChanged();
				this.OnPropertyChanged("Runtime");
            }
        }		 	
		private  global::System.Nullable<int> _Runtime;
        partial void OnRuntimeChanging(global::System.Nullable<int> value);
        partial void OnRuntimeChanged();

		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
	
	}
	
}
	     
