/* 
    Copyright (c) 2012 - 2013 Microsoft Corporation.  All rights reserved.
    Use of this sample source code is subject to the terms of the Microsoft license 
    agreement under which you licensed this sample source code and is provided AS-IS.
    If you did not accept the terms of the license agreement, you are not authorized 
    to use this sample source code.  For the terms of the license, please see the 
    license agreement between you and Microsoft.
  
    To see all Code Samples for Windows Phone, visit http://code.msdn.microsoft.com/wpapps
  
*/
namespace sdkTrialExperienceWP8CS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdkTrialExperienceWP8CS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trialexperiencewp8.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the current value, {0} mode is simulated on launch and Full mode is simulated on purchase..
        /// </summary>
        public static string BehaviorMessageDebug {
            get {
                return ResourceManager.GetString("BehaviorMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A release build of the code in this sample will have access to a license only when the app is published to the Windows Phone Store. Otherwise, it will report MissingOrRevoked..
        /// </summary>
        public static string BehaviorMessageRelease {
            get {
                return ResourceManager.GetString("BehaviorMessageRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buy buttons are enabled in Trial mode only..
        /// </summary>
        public static string BuyAffordancesMessage {
            get {
                return ResourceManager.GetString("BuyAffordancesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string BuyString {
            get {
                return ResourceManager.GetString("BuyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a debug build of the sample. To customize the simulated purchase experience behavior, initialize the simulatedLicMode field of the TrialExperienceHelper class to a different value..
        /// </summary>
        public static string ConfigurationMessageDebug {
            get {
                return ResourceManager.GetString("ConfigurationMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a release build of the sample. Build with the debug configuration for a simulated purchase experience..
        /// </summary>
        public static string ConfigurationMessageRelease {
            get {
                return ResourceManager.GetString("ConfigurationMessageRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructions.
        /// </summary>
        public static string InstructionsText {
            get {
                return ResourceManager.GetString("InstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode.
        /// </summary>
        public static string ModeString {
            get {
                return ResourceManager.GetString("ModeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To purchase, tap any of the Buy buttons (expect error code 805a0194) or navigate away and back..
        /// </summary>
        public static string ToPurchaseMessageDebug {
            get {
                return ResourceManager.GetString("ToPurchaseMessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To purchase, tap any of the Buy buttons..
        /// </summary>
        public static string ToPurchaseMessageRelease {
            get {
                return ResourceManager.GetString("ToPurchaseMessageRelease", resourceCulture);
            }
        }
    }
}
