/* 
    Copyright (c) 2012 - 2013 Microsoft Corporation.  All rights reserved.
    Use of this sample source code is subject to the terms of the Microsoft license 
    agreement under which you licensed this sample source code and is provided AS-IS.
    If you did not accept the terms of the license agreement, you are not authorized 
    to use this sample source code.  For the terms of the license, please see the 
    license agreement between you and Microsoft.
  
    To see all Code Samples for Windows Phone, visit http://code.msdn.microsoft.com/wpapps
  
*/
namespace sdkBasicStorageRecipesWP8CS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdkBasicStorageRecipesWP8CS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC STORAGE RECIPES.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete test files and folders.
        /// </summary>
        public static string ButtonCaptionCleanup {
            get {
                return ResourceManager.GetString("ButtonCaptionCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file in local folder.
        /// </summary>
        public static string ButtonCaptionCreateFile {
            get {
                return ResourceManager.GetString("ButtonCaptionCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder in local folder.
        /// </summary>
        public static string ButtonCaptionCreateFolder {
            get {
                return ResourceManager.GetString("ButtonCaptionCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy existing photo to local folder.
        /// </summary>
        public static string ButtonCaptionExistingPhoto {
            get {
                return ResourceManager.GetString("ButtonCaptionExistingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get contents of app install folder.
        /// </summary>
        public static string ButtonCaptionInstallationFolder {
            get {
                return ResourceManager.GetString("ButtonCaptionInstallationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get contents of app local folder.
        /// </summary>
        public static string ButtonCaptionLocalFolder {
            get {
                return ResourceManager.GetString("ButtonCaptionLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new photo (F7 in Emulator) to local folder.
        /// </summary>
        public static string ButtonCaptionNewPhoto {
            get {
                return ResourceManager.GetString("ButtonCaptionNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read text file from local folder.
        /// </summary>
        public static string ButtonCaptionReadTextFile {
            get {
                return ResourceManager.GetString("ButtonCaptionReadTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write text file in local folder.
        /// </summary>
        public static string ButtonCaptionWriteTextFile {
            get {
                return ResourceManager.GetString("ButtonCaptionWriteTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recipes.
        /// </summary>
        public static string PageNameMainPage {
            get {
                return ResourceManager.GetString("PageNameMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output.
        /// </summary>
        public static string PageNameOutputPage {
            get {
                return ResourceManager.GetString("PageNameOutputPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is sample text saved to a text file in the local folder..
        /// </summary>
        public static string TextFileContent {
            get {
                return ResourceManager.GetString("TextFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string TextFileNotFoundExceptionCaption {
            get {
                return ResourceManager.GetString("TextFileNotFoundExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a new text file before you try to read its contents..
        /// </summary>
        public static string TextFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TextFileNotFoundExceptionMessage", resourceCulture);
            }
        }
    }
}
