/* 
    Copyright (c) 2011 Microsoft Corporation.  All rights reserved.
    Use of this sample source code is subject to the terms of the Microsoft license 
    agreement under which you licensed this sample source code and is provided AS-IS.
    If you did not accept the terms of the license agreement, you are not authorized 
    to use this sample source code.  For the terms of the license, please see the 
    license agreement between you and Microsoft.
  
    To see all Code Samples for Windows Phone, visit http://go.microsoft.com/fwlink/?LinkID=219604 
  
*/
namespace sdkGlobalizationCS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdkGlobalizationCS.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech, Czech Republic.
        /// </summary>
        public static string LangRegionNameCsCZ {
            get {
                return ResourceManager.GetString("LangRegionNameCsCZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish, Denmark.
        /// </summary>
        public static string LangRegionNameDaDK {
            get {
                return ResourceManager.GetString("LangRegionNameDaDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German, Germany.
        /// </summary>
        public static string LangRegionNameDeDE {
            get {
                return ResourceManager.GetString("LangRegionNameDeDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek, Greece.
        /// </summary>
        public static string LangRegionNameElGR {
            get {
                return ResourceManager.GetString("LangRegionNameElGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English, United Kingdom.
        /// </summary>
        public static string LangRegionNameEnGB {
            get {
                return ResourceManager.GetString("LangRegionNameEnGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English, United States.
        /// </summary>
        public static string LangRegionNameEnUS {
            get {
                return ResourceManager.GetString("LangRegionNameEnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish, Spain.
        /// </summary>
        public static string LangRegionNameEsES {
            get {
                return ResourceManager.GetString("LangRegionNameEsES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish, Finland.
        /// </summary>
        public static string LangRegionNameFiFI {
            get {
                return ResourceManager.GetString("LangRegionNameFiFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French, France.
        /// </summary>
        public static string LangRegionNameFrFR {
            get {
                return ResourceManager.GetString("LangRegionNameFrFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian, Hungary.
        /// </summary>
        public static string LangRegionNameHuHU {
            get {
                return ResourceManager.GetString("LangRegionNameHuHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian, Italy.
        /// </summary>
        public static string LangRegionNameItIT {
            get {
                return ResourceManager.GetString("LangRegionNameItIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese, Japan.
        /// </summary>
        public static string LangRegionNameJaJP {
            get {
                return ResourceManager.GetString("LangRegionNameJaJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean, Korea.
        /// </summary>
        public static string LangRegionNameKoKR {
            get {
                return ResourceManager.GetString("LangRegionNameKoKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian, Norway.
        /// </summary>
        public static string LangRegionNameNbNO {
            get {
                return ResourceManager.GetString("LangRegionNameNbNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch, Netherlands.
        /// </summary>
        public static string LangRegionNameNlNL {
            get {
                return ResourceManager.GetString("LangRegionNameNlNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish, Poland.
        /// </summary>
        public static string LangRegionNamePlPL {
            get {
                return ResourceManager.GetString("LangRegionNamePlPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugese, Brazil.
        /// </summary>
        public static string LangRegionNamePtBR {
            get {
                return ResourceManager.GetString("LangRegionNamePtBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugese, Portugal.
        /// </summary>
        public static string LangRegionNamePtPT {
            get {
                return ResourceManager.GetString("LangRegionNamePtPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian, Russia.
        /// </summary>
        public static string LangRegionNameRuRU {
            get {
                return ResourceManager.GetString("LangRegionNameRuRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish, Sweden.
        /// </summary>
        public static string LangRegionNameSvSE {
            get {
                return ResourceManager.GetString("LangRegionNameSvSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified, PRC.
        /// </summary>
        public static string LangRegionNameZhCN {
            get {
                return ResourceManager.GetString("LangRegionNameZhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional, Taiwan.
        /// </summary>
        public static string LangRegionNameZhTW {
            get {
                return ResourceManager.GetString("LangRegionNameZhTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Format:.
        /// </summary>
        public static string TextLabelCurrency {
            get {
                return ResourceManager.GetString("TextLabelCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Language:.
        /// </summary>
        public static string TextLabelDispLang {
            get {
                return ResourceManager.GetString("TextLabelDispLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Date format:.
        /// </summary>
        public static string TextLabelLngDate {
            get {
                return ResourceManager.GetString("TextLabelLngDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Format:.
        /// </summary>
        public static string TextLabelLngTime {
            get {
                return ResourceManager.GetString("TextLabelLngTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Locale:.
        /// </summary>
        public static string TextLabelLocale {
            get {
                return ResourceManager.GetString("TextLabelLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Format:.
        /// </summary>
        public static string TextLabelRegionFormat {
            get {
                return ResourceManager.GetString("TextLabelRegionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Date Format:.
        /// </summary>
        public static string TextLabelShrtDate {
            get {
                return ResourceManager.GetString("TextLabelShrtDate", resourceCulture);
            }
        }
    }
}
