//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixPresenterPortableLib {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixPresenterPortableLib.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixPresenter.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Caption_AppBarConnect {
            get {
                return ResourceManager.GetString("Caption_AppBarConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Caption_AppBarConvert {
            get {
                return ResourceManager.GetString("Caption_AppBarConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Caption_AppBarDisconnect {
            get {
                return ResourceManager.GetString("Caption_AppBarDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from peer.
        /// </summary>
        public static string Caption_Disconnected {
            get {
                return ResourceManager.GetString("Caption_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to send picture.
        /// </summary>
        public static string Caption_Send {
            get {
                return ResourceManager.GetString("Caption_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to connect.
        /// </summary>
        public static string Caption_TapToConnect {
            get {
                return ResourceManager.GetString("Caption_TapToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer connected for picture sharing.
        /// </summary>
        public static string Message_Disconnected {
            get {
                return ResourceManager.GetString("Message_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string PageTitle_Albums {
            get {
                return ResourceManager.GetString("PageTitle_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture viewer.
        /// </summary>
        public static string PageTitle_Picture {
            get {
                return ResourceManager.GetString("PageTitle_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that Bluetooth is enabled.
        /// </summary>
        public static string VerifyBluetooth {
            get {
                return ResourceManager.GetString("VerifyBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string W8_AlternateIdentifier {
            get {
                return ResourceManager.GetString("W8_AlternateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b3c3e7ef-371a-464f-a75e-95ddbdcaf974_7fed2v891h66p!App.
        /// </summary>
        public static string W8_AlternateIdentity {
            get {
                return ResourceManager.GetString("W8_AlternateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsPhone.
        /// </summary>
        public static string WP8_AlternateIdentifier {
            get {
                return ResourceManager.GetString("WP8_AlternateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1c6379c1-9d5e-4254-8f4c-be7ea24057d1}.
        /// </summary>
        public static string WP8_AlternateIdentity {
            get {
                return ResourceManager.GetString("WP8_AlternateIdentity", resourceCulture);
            }
        }
    }
}
