/* 
    Copyright (c) 2012 Microsoft Corporation.  All rights reserved.
    Use of this sample source code is subject to the terms of the Microsoft license 
    agreement under which you licensed this sample source code and is provided AS-IS.
    If you did not accept the terms of the license agreement, you are not authorized 
    to use this sample source code.  For the terms of the license, please see the 
    license agreement between you and Microsoft.
  
    To see all Code Samples for Windows Phone, visit http://go.microsoft.com/fwlink/?LinkID=219604 
  
*/
namespace sdkWalletPaymentInstrumentsWP8CS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sdkWalletPaymentInstrumentsWP8CS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTOSO BANK.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while loading your card information..
        /// </summary>
        public static string CardLoadError {
            get {
                return ResourceManager.GetString("CardLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing your card:.
        /// </summary>
        public static string CardRemoveError {
            get {
                return ResourceManager.GetString("CardRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while saving your card:.
        /// </summary>
        public static string CardSaveError {
            get {
                return ResourceManager.GetString("CardSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Wallet.
        /// </summary>
        public static string InWalletStatus {
            get {
                return ResourceManager.GetString("InWalletStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string NegativeTransactionSymbol {
            get {
                return ResourceManager.GetString("NegativeTransactionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In Wallet.
        /// </summary>
        public static string NotInWalletStatus {
            get {
                return ResourceManager.GetString("NotInWalletStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pay bill.
        /// </summary>
        public static string PayBillButtonText {
            get {
                return ResourceManager.GetString("PayBillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PositiveTransactionSymbol {
            get {
                return ResourceManager.GetString("PositiveTransactionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from wallet.
        /// </summary>
        public static string RemoveFromWalletButtonText {
            get {
                return ResourceManager.GetString("RemoveFromWalletButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save to wallet.
        /// </summary>
        public static string SaveToWalletButtonText {
            get {
                return ResourceManager.GetString("SaveToWalletButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view bill.
        /// </summary>
        public static string ViewBillButtonText {
            get {
                return ResourceManager.GetString("ViewBillButtonText", resourceCulture);
            }
        }
    }
}
